/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Db.Dbcon;
import General.Configuration;
import General.Nimbus;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Jithinpv
 */
public class UploadFile extends javax.swing.JFrame {

    public static int encryption_id = 0;

    /**
     * Creates new form UploadFile
     */
    public UploadFile() {
        Nimbus.loadLoogAndFeel();
        initComponents();
        this.setLocationRelativeTo(null);
         Configuration.setIconOnLabel("chooseFile.jpg", bg);
    }

    public UploadFile(String attr_1, String attr_2, String attr_3, String attr_4, String privateKey, String masterKey, String secretKey) {
        Nimbus.loadLoogAndFeel();
        initComponents();
        this.setLocationRelativeTo(null);
        attribute_1.setText(attr_1);
        attribute_2.setText(attr_2);
        attribute_3.setText(attr_3);
        attribute_4.setText(attr_4);
        private_key_text.setText(privateKey);
        master_key_text.setText(masterKey);
        secret_key_text.setText(secretKey);
        Configuration.setIconOnLabel("chooseFile.jpg", bg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        attribute_1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        attribute_2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        attribute_3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        attribute_4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        private_key_text = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        master_key_text = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        secret_key_text = new javax.swing.JTextField();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Upload File");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 25, 66, -1));

        jLabel3.setText("Attribute 1");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 60, 116, -1));

        attribute_1.setEditable(false);
        getContentPane().add(attribute_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 57, 141, -1));

        jLabel4.setText("Attribute 2");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 98, 116, -1));

        attribute_2.setEditable(false);
        getContentPane().add(attribute_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 95, 141, -1));

        jLabel5.setText("Attribute 3");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 136, 116, -1));

        attribute_3.setEditable(false);
        getContentPane().add(attribute_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 133, 141, -1));

        jLabel6.setText("Attribute 4");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 174, 116, -1));

        attribute_4.setEditable(false);
        getContentPane().add(attribute_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 171, 141, -1));

        jButton2.setText("Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 348, 141, -1));

        jLabel7.setText("Private  Key");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 212, 77, -1));

        private_key_text.setEditable(false);
        getContentPane().add(private_key_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 209, 141, -1));

        jLabel8.setText("Mater Key");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 250, 77, -1));

        master_key_text.setEditable(false);
        getContentPane().add(master_key_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 247, 141, -1));

        jLabel9.setText("Secret Key");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 288, 77, -1));

        secret_key_text.setEditable(false);
        getContentPane().add(secret_key_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 285, 141, -1));

        bg.setText("jLabel2");
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 390, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new DataMemberHome().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UploadFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UploadFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UploadFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UploadFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new UploadFile().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField attribute_1;
    private javax.swing.JTextField attribute_2;
    private javax.swing.JTextField attribute_3;
    private javax.swing.JTextField attribute_4;
    private javax.swing.JLabel bg;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField master_key_text;
    private javax.swing.JTextField private_key_text;
    private javax.swing.JTextField secret_key_text;
    // End of variables declaration//GEN-END:variables
}
