/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Db.Dbcon;
import General.Configuration;
import General.Nimbus;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jithinpv
 */
public class ViewTransferHistory extends javax.swing.JFrame {

    /**
     * Creates new form ViewTransferHistory
     */
    public ViewTransferHistory() {
         Nimbus.loadLoogAndFeel();
        initComponents();
        this.setLocationRelativeTo(null);
        viewTransferHistory();
         Configuration.setIconOnLabel("createOrg.jpg", bg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        sender_org = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        receiver_org = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        size = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        type = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        priorityy = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("History");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 11, 70, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "SENDER", "RECEIVER", "FILE", "DATE", "STATUS"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 43, 430, 145));

        jLabel2.setText("Sender Organization");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 262, -1, -1));
        getContentPane().add(sender_org, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 259, 138, -1));

        jLabel3.setText("Receiver Organization");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 300, -1, -1));
        getContentPane().add(receiver_org, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 297, 138, -1));

        jLabel4.setText("File Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 335, 106, -1));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 335, 138, -1));

        jLabel5.setText("File Size");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 373, 97, -1));
        getContentPane().add(size, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 373, 138, -1));

        jLabel6.setText("File Type");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 411, 97, -1));
        getContentPane().add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 411, 138, -1));

        jLabel7.setText("Priority");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 449, 97, -1));
        getContentPane().add(priorityy, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 449, 138, -1));

        jButton1.setText("HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 218, -1, -1));

        bg.setText("jLabel8");
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 480, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        AdminHome adminHome = new AdminHome();
        adminHome.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        Dbcon dbcon = new Dbcon();
        String reqid = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
        String qury = "SELECT  filereq.request_id,filereq.request_priority, filereq.requested_data_member ,datam.name AS dataMemName, org.name AS org_name, encrptlog.attr_1 ,encrptlog.attr_2,encrptlog.attr_3,datam2.name AS dataOwnerName, org2.name AS dataOwnweOrg FROM   tbl_file_request AS filereq ,tbl_data_member AS datam ,  tbl_organisation AS org,  tbl_data_member AS datam2 ,  tbl_organisation AS org2,  tbl_file_encryption_logs AS encrptlog WHERE   filereq.requested_data_member = datam.data_member_id  and org.organisation_id = datam.organization_id AND  encrptlog.encryption_id = filereq.encryption_id AND  datam2.data_member_id = filereq.file_owner_data_member AND org2.organisation_id = datam2.organization_id and filereq.request_id='" + reqid + "'";
        System.out.println(qury);
        ResultSet rs = dbcon.select(qury);
        try {
            if (rs.next()) {
                String fileName = rs.getString("attr_1");
                String fileSize = rs.getString("attr_2");
                String fileType = rs.getString("attr_3");
                String senderOrg = rs.getString("dataOwnweOrg");
                String receiverOrg = rs.getString("org_name");
                String priority = rs.getString("request_priority");
                if (priority.equals("1")) {
                    priority = "low";
                } else if (priority.equals("2")) {
                    priority = "medium";
                } else {
                    priority = "high";
                }
                sender_org.setText(senderOrg);
                receiver_org.setText(receiverOrg);
                name.setText(fileName);
                size.setText(fileSize);
                type.setText(fileType);
                priorityy.setText(priority);

            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_jTable1MouseClicked
    private void viewTransferHistory() {
       
        Dbcon dbcon = new Dbcon();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String arr[] = new String[7];
        String query = "SELECT filereq.request_id,filereq.requested_date, filereq.request_priority, filereq.requested_data_member ,filereq.status,datam.name AS dataMemName, org.name AS org_name, encrptlog.attr_1 ,encrptlog.attr_2,encrptlog.attr_3,datam2.name AS dataOwnerName, org2.name AS dataOwnweOrg FROM   tbl_file_request AS filereq ,tbl_data_member AS datam ,  tbl_organisation AS org,  tbl_data_member AS datam2 ,  tbl_organisation AS org2,  tbl_file_encryption_logs AS encrptlog WHERE   filereq.requested_data_member = datam.data_member_id  and org.organisation_id = datam.organization_id AND  encrptlog.encryption_id = filereq.encryption_id AND  datam2.data_member_id = filereq.file_owner_data_member AND org2.organisation_id = datam2.organization_id";
        ResultSet rs = dbcon.select(query);
        try {
            while (rs.next()) {
                
                String reqId = rs.getString("request_id");
                String receiver = rs.getString("dataMemName");
                String sender = rs.getString("dataOwnerName");
                String file = rs.getString("attr_1");
                String date = rs.getString("requested_date");
                String status = rs.getString("status");
                if (status.equals("0")) {
                    status = "rejected";
                } else if (status.equals("1")) {
                    status = "approved";
                } else {
                    status = "pending";
                }
                arr[0] = reqId;
                arr[2] = sender;
                arr[1] = receiver;
                arr[3] = getFormatedDate(date, "dd MM yyyy");
                arr[4] = status;
                arr[5] = file;
                //arr[6] = encId;
                model.addRow(arr);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private String getFormatedDate(String dateString, String format) {

        try {
            long dateMilli = Long.parseLong(dateString);
            Date date = new Date(dateMilli);
            SimpleDateFormat formatter = new SimpleDateFormat(format);

            String formatted = formatter.format(date);

            System.out.println("formatted " + formatted);
            return formatted;
        } catch (Exception e) {
            return "date not found";
        }

    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTransferHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTransferHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTransferHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTransferHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewTransferHistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField priorityy;
    private javax.swing.JTextField receiver_org;
    private javax.swing.JTextField sender_org;
    private javax.swing.JTextField size;
    private javax.swing.JTextField type;
    // End of variables declaration//GEN-END:variables
}
